/* tslint:disable */
/* eslint-disable */
/**
 * people-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Title = {
    Miss: 'Miss',
    Mr: 'Mr.',
    Ms: 'Ms.'
} as const;
export type Title = typeof Title[keyof typeof Title];


export function instanceOfTitle(value: any): boolean {
    for (const key in Title) {
        if (Object.prototype.hasOwnProperty.call(Title, key)) {
            if (Title[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TitleFromJSON(json: any): Title {
    return TitleFromJSONTyped(json, false);
}

export function TitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Title {
    return json as Title;
}

export function TitleToJSON(value?: Title | null): any {
    return value as any;
}

